### ISSUE TITLE
MongoDB error

### ISSUE THREAD

**Issue by pdotsani** [child-first-authority-fcc-project/vagrantbox#7]
After recently updating my local version of the vagrantbox, I ran `grunt serve` and came across this error:

``` terminal
MongoDB connection error: MongoError: connect ECONNREFUSED
```

**Comment by dting** [comment]
This happens when the vm isn't powered down correctly, usually due to the host system restarting or shutting down while the vm is running. 

https://docs.mongodb.org/manual/tutorial/recover-data-following-unexpected-shutdown/
